<header>
  <DeviceLog>
    <Header>
      <Duration>3420</Duration>
      <DateTime>2023-10-21T12:13:38Z</DateTime>
      <Activity>Diving</Activity>
      <Device>
        <Name>Suunto Ambit2</Name>
        <SerialNumber>12345678</SerialNumber>
        <Info>
          <SW>2.5.15</SW>
        </Info>
      </Device>
    </Header>
    <Samples>
      <Sample>
        <Time>0</Time>
        <Depth>0.0</Depth>
        <Temperature>298.15</Temperature>
        <Pressure>101300</Pressure>
      </Sample>
      <Sample>
        <Time>10</Time>
        <Depth>5.2</Depth>
        <Temperature>297.85</Temperature>
        <Pressure>153300</Pressure>
      </Sample>
      <Sample>
        <Time>20</Time>
        <Depth>10.5</Depth>
        <Temperature>295.15</Temperature>
        <Pressure>206300</Pressure>
      </Sample>
    </Samples>
  </DeviceLog>
</header>
